API-1251: Update documentation to get categories filtered by parent
akeneo/pim-api-docs pull request #403
Opened 2020-08-05 08:06 UTC by pierrejolly

2020-08-10 09:02 UTC, meganelepalud-akeneo commented on content/rest-api/filter.md
> +/api/rest/v1/categories?search={"type":[{"operator":"IN","value":["categoryA","categoryB"]}]}
```suggestion
/api/rest/v1/categories?search={"parent":[{"operator":"IN","value":["categoryA","categoryB"]}]}
```

2020-08-10 09:03 UTC, meganelepalud-akeneo commented on content/rest-api/filter.md
> +You can filter the categories by their parents.
```suggestion
You can filter the categories on their parents. When you add a parent category in the filter, the response will contain all its child sub-categories. 
```

2020-08-10 09:04 UTC, meganelepalud-akeneo commented on content/rest-api/filter.md
> +To get the categories of parents `categoryA` and `categoryB`, you can use the following URL.
```suggestion
To get the child categories of parents `categoryA` and `categoryB`, you can use the following URL.
```

2020-08-10 09:06 UTC, meganelepalud-akeneo commented on content/rest-api/filter.md
> +### By categories parents
```suggestion
### On parent categories
```

2020-08-19 07:45 UTC, meganelepalud-akeneo requested changes

2020-08-19 07:45 UTC, meganelepalud-akeneo commented on content/rest-api/filter.md
> +| `IN` | an array of [existing categories parents](/concepts/catalog-structure.html#category) | Only returns the categories of the given parents |
```suggestion
| `=` | a string containing an [existing parent category](/concepts/catalog-structure.html#category) | Only returns the sub-categories of the given parent |
```

2020-08-19 07:45 UTC, meganelepalud-akeneo commented on content/rest-api/filter.md
> +To get the child categories of parents `categoryA` and `categoryB`, you can use the following URL.
```suggestion
To get the child categories of the parent category `categoryA`, you can use the following URL.
```

2020-08-19 07:45 UTC, meganelepalud-akeneo commented on content/rest-api/filter.md
> +/api/rest/v1/categories?search={"parent":[{"operator":"IN","value":["categoryA","categoryB"]}]}
```suggestion
/api/rest/v1/categories?search={"parent":[{"operator":"=","value":"categoryA"}]}
```

2020-08-20 14:03 UTC, meganelepalud-akeneo approved these changes

2020-08-25 08:04 UTC, NolwennP commented on content/rest-api/filter.md
> +### By category parent
```suggestion
### By parent category
```

2020-08-26 11:51 UTC, fitn approved these changes

2020-09-11 13:24 UTC, merged