API-1565: add "is_root" search filter
akeneo/pim-api-docs pull request #483
Opened 2021-05-04 12:13 UTC by pchasle

Add documentation of the filter to get root or non-root categories only.

2021-05-04 12:23 UTC, tomglvng approved these changes

2021-05-04 16:43 UTC, meganelepalud-akeneo requested changes

2021-05-04 16:43 UTC, meganelepalud-akeneo commented on content/rest-api/filter.md
> +You can filter the categories to get only root categories or non-root categories.
```suggestion
You can filter the categories to get only root categories or non-root categories. Root categories can also be called Category trees. 
```

2021-05-04 16:43 UTC, meganelepalud-akeneo commented on content/rest-api/filter.md
> +/api/rest/v1/categories?search={"IS_ROOT":[{"operator":"=","value":true}]}
```suggestion
/api/rest/v1/categories?search={"is_root":[{"operator":"=","value":true}]}
```
I tried with IS_ROOT and I have an error message: "Available search filters are \"code, parent, is_root\" and you tried to search on unavailable filter \"IS_ROOT\""

2021-05-04 16:43 UTC, meganelepalud-akeneo commented on content/rest-api/filter.md
> +| `=` | boolean | Only returns categories that are root (`true`) or non-root (`false`) |
```suggestion
| `=` | boolean | When `true`, only returns categories that are root. When `false`, returns any other categories. |
```

2021-05-04 16:43 UTC, meganelepalud-akeneo commented on content/rest-api/filter.md
> +
```suggestion

::: tips
You can combine the `is_root` filter with any other filter available on categories.
:::

```

2021-05-04 16:44 UTC, meganelepalud-akeneo commented
I have a meeting with Camille tomorrow, I'll show her this PR. ;)

2021-05-05 08:40 UTC, fitn approved these changes

2021-05-05 08:40 UTC, fitn commented on content/rest-api/filter.md
> +You can filter the categories to get only root categories or non-root categories. Root categories can also be called Category trees.
```suggestion
You can filter the categories to get only root categories or non-root categories.
```

A root category is the base of the category tree. The category tree is a root category + some categories

2021-05-05 11:57 UTC, tseho commented on content/rest-api/filter.md
> +### By root category
`By root category` is a little confusing for me.
At first glance, I think it means that I'm able to filter on a root category.
Something like `?root=clothes` and receives all the categories of the tree under this root.

Maybe `By root only` ?

2021-05-07 09:20 UTC, camillebourjade approved these changes

2021-05-07 09:21 UTC, meganelepalud-akeneo approved these changes

2021-05-07 09:21 UTC, merged