Document 'parent' filter for products and product models
akeneo/pim-api-docs pull request #487
Opened 2021-05-10 07:59 UTC by mmetayer

Documents the `parent` filter for products and product models, see https://github.com/akeneo/pim-community-dev/pull/14442

for products:
- add `IN`, `EMPTY` and `NOT EMPTY` as valid operators
- the `=` operator is still available

for product models:
- add `IN`, `EMPTY` and `NOT EMPTY` as valid operators

2021-05-11 09:22 UTC, meganelepalud-akeneo requested changes

2021-05-11 09:23 UTC, meganelepalud-akeneo commented on content/rest-api/filter.md
> +::: availability versions=Serenity editions=CE,EE
I have an in progress PR that changes Serenity to SaaS => this will avoid a future fix ;)

2021-05-11 12:04 UTC, mmetayer commented on content/rest-api/filter.md
:ok: I'll add a commit as soon as I can

2021-05-18 09:27 UTC, meganelepalud-akeneo commented on content/rest-api/filter.md
> +/api/rest/v1/products?search={"parent":[{"operator":"IN","value":["tshirt_armor"]}]}
```suggestion
/api/rest/v1/product-models?search={"parent":[{"operator":"IN","value":["tshirt_armor"]}]}
```

2021-05-18 09:27 UTC, meganelepalud-akeneo commented on content/rest-api/filter.md
> +/api/rest/v1/products?search={"parent":[{"operator":"EMPTY"}]}
```suggestion
/api/rest/v1/product-models?search={"parent":[{"operator":"EMPTY"}]}
```

2021-05-18 09:27 UTC, meganelepalud-akeneo commented on content/rest-api/filter.md
> +/api/rest/v1/products?search={"parent":[{"operator":"NOT EMPTY"}]}
```suggestion
/api/rest/v1/product-models?search={"parent":[{"operator":"NOT EMPTY"}]}
```

2021-05-18 09:53 UTC, mmetayer commented on content/rest-api/filter.md
> +/api/rest/v1/products?search={"parent":[{"operator":"IN","value":["tshirt_armor"]}]}
oops, sorry :/

2021-06-01 15:12 UTC, meganelepalud-akeneo approved these changes

2021-06-01 15:24 UTC, merged