Fix references to #focus-on-the-product-values
akeneo/pim-api-docs pull request #550
Opened 2022-01-28 16:02 UTC by DavidePastore

I saw there were different links pointing to the wrong fragment.

2022-03-01 12:41 UTC, meganelepalud-akeneo approved these changes

2022-03-29 16:14 UTC, LevFlavien requested changes
Hi @DavidePastore

Thank you for your contribution! Could you please rebase/update your branch and regenerate 
a fresh `akeneo-web-api.json` to remove merge conflicts please?

Regards

2022-03-30 11:10 UTC, DavidePastore commented
Hi @LevFlavien. I made the changes you requested 😄

2022-03-30 12:40 UTC, LevFlavien approved these changes

2022-03-30 12:40 UTC, LevFlavien commented
Great, thank you

2022-03-30 12:41 UTC, merged