API-1637: Add the creation and update date of a Ref. entity
akeneo/pim-api-docs pull request #567
Opened 2022-03-21 16:40 UTC by dFayet

related to : https://github.com/akeneo/pim-enterprise-dev/pull/13211

2022-03-22 09:29 UTC, LevFlavien requested changes
Add readonly properties on PATCH routes

2022-03-22 09:35 UTC, LevFlavien commented on content/swagger/resources/reference_entity_records/definitions/reference_entity_record.yaml
> +      default: null
immutable property (see Product for example)

2022-03-22 09:53 UTC, benjaminleneve commented on content/swagger/resources/reference_entity_records/definitions/reference_entity_record.yaml
> +  update:
Replace update with updated

2022-03-22 09:53 UTC, benjaminleneve commented on content/swagger/resources/reference_entity_records/definitions/reference_entity_record.yaml
> +      default: null
Add read-only attribute for created and updated

2022-03-22 13:48 UTC, benjaminleneve approved these changes

2022-03-23 09:20 UTC, LevFlavien commented on content/swagger/resources/reference_entity_records/definitions/reference_entity_record.yaml
> +      description: Date of the last update
Add "(Only available on SaaS platforms)" to both descriptions

2022-03-23 09:27 UTC, LevFlavien commented on content/swagger/resources/reference_entity_records/definitions/reference_entity_record.yaml
> +      description: Date of the last update
FYI When v7 is released, all this kind of message will be cleaned up

2022-03-23 10:14 UTC, SamirBoulil approved these changes

2022-04-05 11:38 UTC, merged