[On Hold] - PHP client product UUID update
akeneo/pim-api-docs pull request #645
Opened 2022-08-22 15:59 UTC by tomglvng

2022-09-15 14:42 UTC, LevFlavien requested changes
Getting started page has a code sample
```
$product = $client->getProductApi()->get('top');
echo $product['identifier'];
```
We should promote UUIDs instead.

TODO: Parse doc and switch Product code example to Product-UUID

2022-09-29 12:34 UTC, LevFlavien approved these changes

2022-09-29 12:43 UTC, pierallard approved these changes

2022-09-29 12:43 UTC, pierallard commented on content/php-client/resources/products/product-drafts-uuid.md
> + *              [
You should have a "sku" value here.

2022-09-29 12:43 UTC, pierallard commented on content/php-client/resources/products/products-uuid.md
> + *         'name' => [
Same

2022-09-29 12:43 UTC, pierallard commented on content/php-client/resources/products/products-uuid.md
> +Setting the parameter `with_count`  to `true`  can drastically decrease the performance.
```suggestion
Setting the parameter `with_count`  to `true` can drastically decrease the performance.  
```

2022-09-29 12:43 UTC, pierallard commented on content/php-client/resources/products/products-uuid.md
> +        'name' => [
same

2022-09-29 12:43 UTC, pierallard commented on content/php-client/resources/products/products-uuid.md
> +        'name' => [
etc

2022-09-29 12:49 UTC, LevFlavien commented on content/php-client/resources/products/products-uuid.md
> +        'name' => [
ty

2022-09-29 12:51 UTC, merged