CXP-1375: other method to add link between type:string and format property
akeneo/pim-api-docs pull request #749
Opened 2023-01-19 15:20 UTC by hogren

2023-01-20 09:27 UTC, masacc commented on content/mapping/product/0.0.4/schema
> +    },
useless

2023-01-20 09:28 UTC, masacc commented
Nice solution, we can apply it in next version of the schema. GG @hogren

2023-01-27 13:56 UTC, masacc commented
@hogren you can close this PR but we will use this solution for next version (0.0.5). The 0.0.4 version is already merged on master-octopus

2023-01-31 14:18 UTC, tseho requested changes
the documentation should contains only a copy of the schema from pim-community-dev, they should be identical, the changes should be in CE first in newer schema versions.

2023-02-23 10:57 UTC, closed without merging