[CHA-791] AEP GA API ref subscribers
akeneo/pim-api-docs pull request #921
Opened 2024-08-09 14:33 UTC by JulienVerbrugge

only the base routing is set it remains to:
- create api ref files in /swagger 
- remove the version dropdown form the page

2024-08-12 05:32 UTC, hogren commented on content/swagger/resources/subscribers/routes/subscribers.yaml
> +    - "7.0"
I don't think.

2024-08-13 15:47 UTC, akeneo-secops commented
### Gitleaks PR check
🟢 We detected no secrets within this PR! Good job 🎉

2024-08-16 11:44 UTC, hogren requested changes
Il manque la partie BODY des POST et PATCH. 
Il y a un fichier qui je pense n'est pas utilisé : content/swagger/resources/subscribers/routes/subscribers.yaml
Besoin d'une mob review pour ma part please :pray:

2024-08-19 14:57 UTC, AdelELHAIBA-Akeneo commented on src/partials/layout.handlebars
> +                                <li><a href="/akeneo-event-platform/api-reference.html">Management API Reference</a></li>
Est-ce qu'on appelle ça ainsi ? ou juste API Reference ?

2024-08-21 13:39 UTC, clovis-akeneo approved these changes

2024-08-21 13:56 UTC, AdelELHAIBA-Akeneo approved these changes

2024-08-22 07:07 UTC, guillaumefer-akeneo approved these changes

2024-08-22 07:35 UTC, hogren approved these changes

2024-08-22 07:36 UTC, merged